module.exports = {
    FEATURES: {
        Domain_Length: 0,
        Subdomain_Level: 1,
        Have_At_Sign: 2,
        Have_Tilde_Symbol: 3,
        No_Https: 4,
        Having_IP: 5,
        Http_In_Hostname: 6,
        Double_Slash_In_Path: 7,
        // Num_Dots: 8,
        // Num_Dashes_In_Hostname: 9,
        // Num_Underscore: 10,
        // Num_Percent: 11,
        // Num_Ampersand: 12,
        // Num_Hash: 13,
        // Num_Numeric_Chars: 14,
        // Num_Sensitive_Words: 15,
        Ext_Favicon: 16,
        Redirection: 17,
        Tiny_URL: 18,
        Prefix_Suffix: 19,
        DNS: 20,
        Domain_Age: 21,
        Domain_End: 22,
        Rank_Host: 23,
        Rank_Country: 24,
        Iframe: 25,
        Mouse_Over: 26,
        Right_Click: 27,
        Forwarding: 28
    }
}