module.exports = {
    FEATURES: {
        Domain_Length: 0,
        Subdomain_Level: 1,
        Have_At_Sign: 2,
        Have_Tilde_Symbol: 3,
        No_Https: 4,
        Having_IP: 5,
        Domain_In_Subdomains: 6,
        Domain_In_Paths: 7,
        Http_In_Hostname: 8,
        Double_Slash_In_Path: 9,
        // Num_Dots: 10,
        // Num_Dashes_In_Hostname: 11,
        // Num_Underscore: 12,
        // Num_Percent: 13,
        // Num_Query_Components: 14,
        // Num_Ampersand: 15,
        // Num_Hash: 16,
        // Num_Numeric_Chars: 17,
        // Num_Sensitive_Words: 18,
        Ext_Favicon: 19,
        Redirection: 20,
        Tiny_URL: 21,
        Prefix_Suffix: 22,
        DNS: 23,
        Domain_Age: 24,
        Domain_End: 25,
        Rank_Host: 26,
        Rank_Country: 27,
        Iframe: 28,
        Mouse_Over: 29,
        Right_Click: 30,
        Forwarding: 31
    }
}